### ISSUE TITLE
Clean UP & Dockerization eos78ao

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos78ao#5]

**Comment by pittmanriley** [comment]
Hi @GemmaTuron @miquelduranfrigola, 

I'm having some issues fetching this model. If I fetch in CLI or Codespaces, I get this error: 
[out.log](https://github.com/ersilia-os/eos78ao/files/11998372/out.log)

It mentions something about a syntax error near unexpected token `NO', and I'm not sure what this means. I've tried fetching using the --repo_path and --from_github options, but they get me the same error.

**Comment by miquelduranfrigola** [comment]
Thanks @pittmanriley - I was about to ask exactly this. Before running `run.sh`, have you done `conda activate eos78ao`? Is pandas installed inside `eos78ao` environment?

**Comment by pittmanriley** [comment]
I did this before, but I just tried doing `conda install pandas` rather than `pip install pandas` and it ran this time. However, I reached a long error message: 
[out.log](https://github.com/ersilia-os/eos78ao/files/11998499/out.log)

**Comment by GemmaTuron** [comment]
could be related to Mac: https://stackoverflow.com/questions/67328927/multiprocessing-throwing-runtime-error-after-executing-p-start

Could you try on codespaces?

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, I was able to run run.sh inside Codespaces and the model works. Does this mean I'm able to start refactoring? Or do I need to get it to fetch before I refactor?

**Comment by GemmaTuron** [comment]
Hi @pittmanriley 
If you do not provide the logs of the error we cannot help.

**Comment by pittmanriley** [comment]
@GemmaTuron Sorry about that. After I individually download each package in Codespaces, I run the model using run.sh and it works. However, if I try fetching the model using --repo_path, I get the following error, despite already downloading each of the packages needed. I downloaded the packages within the conda environment eos78ao, and also tried fetching within the environment, so the packages should be installed. 
[out.csv](https://github.com/ersilia-os/eos78ao/files/12011718/out.csv)

**Comment by GemmaTuron** [comment]
Hi @pittmanriley 

It does seem that rdkit is simply not installed - I don't understand the bit "despite already downloading each of the packages needed.". When you fetch a model, it will eliminate any conda environment with the same name and create it anew, so it does not matter which packages you installed previously
`07:02:22 | INFO     | Deleting conda environment eos78ao`
If you want to do manual tests I suggest adding a different name to the env, like eos78ao_manual

If the model works when running run.sh on a manually created environment but not at fetch time it indicates a problem with package installation from the dockerfile instructions. I'd bet for the conda install of rdkit.
I suggest the following changes in the DockerFile for the conda packages
```
pip install rdkit==2023.3.2 (latest version)
pip install mordred==1.2
```

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, these suggestions worked well. I also added a line in the Dockerfile to install pandas, since I kept getting an error in Codespaces saying that the module couldn't be found. After making the refactoring changes and Dockerfile changes, I was able to test the model within Codespaces and it worked well, so I opened a PR.

**Comment by GemmaTuron** [comment]
This seems an Ersilia Issue, I am rerunning the workflows
